%% DIRECTIVES
:-lambdaCut(0.5).
:-fuzzy_rel('~',[reflexive,symmetric]).
% Here, ~ is a proximity relation, it is not transitive

%% PROXIMITY RELATIONS
%% Location Distance Relationship
bervely_hills~downtown=0.3.
bervely_hills~santa_monica=0.45.
bervely_hills~hollywood=0.56.
bervely_hills~westwood=0.9.
downtown~hollywood=0.45.
downtown~santa_monica=0.23.
downtown~westwood=0.25.
hollywood~santa_monica=0.3.
hollywood~westwood=0.45.
santa_monica~westwood=0.9.

%% Category Relationship
comedy~drama=0.6.
comedy~adventure=0.3.
comedy~suspense=0.3.
drama~adventure=0.6.
drama~suspense=0.6.
adventure~suspense=0.9.

%% Films Table
%% film(Title, Director, Category)
film(four_feathers, korda, adventure).
film(modern_times, chaplin, comedy).
film(psycho, hitchcock, suspense).
film(rear_window, hitchcock, suspense).
film(robbery, yates, suspense).
film(star_wars, lucas, adventure).
film(surf_party, dexter, drama).

%% Theaters Table
%% theater(Name,Owner,Location).
theater(chinese,mann,hollywood).
theater(egyptian,va,westwood).
theater(music_hall,lae,bervely_hills).
theater(odeon,cineplex,santa_monica).
theater(rialto,independent,downtown).
theater(village,mann,westwood).

%% Engagements Table
%% engagement(Film,Theater)
engagement(modern_times,rialto).
engagement(start_wars,rialto).
engagement(star_wars,chinese).
engagement(rear_window,egyptian).
engagement(surf_party,village).
engagement(robbery,odeon).
engagement(modern_times,odeon).
engagement(four_feathers,music_hall).

%% MAIN RULE
%% search(input, input, output, output)
search(Category, Location, Film, Theater) :-
	film(Film, _, Category),
	engagement(Film, Theater),
	theater(Theater, _, Location).
	
%% EXAMPLE QUERY
:- solve(search(adventure, westwood, Film, Theater)).

%% Outcome:
% Info: Processing:
%   answer(A,B) :-
%     search(adventure,westwood,A,B).
% {
%   answer(four_feathers,music_hall)with 0.9,
%   answer(rear_window,egyptian)with 0.9,
%   answer(robbery,odeon)with 0.9,
%   answer(surf_party,village)with 0.6
% }
% Info: 4 tuples computed.          
