
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'formulaCOMMA IMPLIES LPAREN NOT NUMBER RPAREN WORDformula : body IMPLIES head \n\t\t\t\t| headbody : term \n\t\t\t| term COMMA bodyhead : termterm : NOT term \n\t\t\t| WORD LPAREN arg_seq RPARENarg_seq : arg \n\t\t\t\t| arg COMMA arg_seqarg : WORD \n\t\t| NUMBER'
    
_lr_action_items = {'IMPLIES':([1,3,10,13,14,19,],[7,-3,-6,-4,-3,-7,]),'RPAREN':([15,16,17,18,21,],[19,-11,-8,-10,-9,]),'NUMBER':([9,20,],[16,16,]),'COMMA':([3,10,14,16,17,18,19,],[8,-6,8,-11,20,-10,-7,]),'LPAREN':([4,],[9,]),'NOT':([0,5,7,8,],[5,5,5,5,]),'WORD':([0,5,7,8,9,20,],[4,4,4,4,18,18,]),'$end':([2,3,6,10,11,12,19,],[-2,-5,0,-6,-1,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,8,],[1,13,]),'head':([0,7,],[2,11,]),'arg_seq':([9,20,],[15,21,]),'term':([0,5,7,8,],[3,10,12,14,]),'arg':([9,20,],[17,17,]),'formula':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> body IMPLIES head','formula',3,'p_formula','Interact.py',113),
  ('formula -> head','formula',1,'p_formula','Interact.py',114),
  ('body -> term','body',1,'p_body_1','Interact.py',118),
  ('body -> term COMMA body','body',3,'p_body_1','Interact.py',119),
  ('head -> term','head',1,'p_head','Interact.py',127),
  ('term -> NOT term','term',2,'p_term','Interact.py',131),
  ('term -> WORD LPAREN arg_seq RPAREN','term',4,'p_term','Interact.py',132),
  ('arg_seq -> arg','arg_seq',1,'p_argseq','Interact.py',139),
  ('arg_seq -> arg COMMA arg_seq','arg_seq',3,'p_argseq','Interact.py',140),
  ('arg -> WORD','arg',1,'p_arg','Interact.py',148),
  ('arg -> NUMBER','arg',1,'p_arg','Interact.py',149),
]
