
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'formulaCOMMA IMPLIES LPAREN NOT NUMBER PRED RPAREN VARformula  : body IMPLIES head \n\t\t\t\t| headbody : term \n\t\t\t| term COMMA bodyhead : termterm : NOT term \n\t\t\t| PRED LPAREN arg_seq RPARENarg_seq  : arg \n\t\t\t\t| arg COMMA arg_seqarg : VAR \n\t\t| NUMBER'
    
_lr_action_items = {'IMPLIES':([1,4,10,17,18,19,],[7,-3,-6,-4,-3,-7,]),'PRED':([0,5,7,9,],[3,3,3,3,]),'NUMBER':([8,20,],[14,14,]),'VAR':([8,20,],[16,16,]),'COMMA':([4,10,14,15,16,18,19,],[9,-6,-11,20,-10,9,-7,]),'LPAREN':([3,],[8,]),'NOT':([0,5,7,9,],[5,5,5,5,]),'RPAREN':([13,14,15,16,21,],[19,-11,-8,-10,-9,]),'$end':([2,4,6,10,11,12,19,],[-2,-5,0,-6,-1,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,9,],[1,17,]),'head':([0,7,],[2,11,]),'arg_seq':([8,20,],[13,21,]),'term':([0,5,7,9,],[4,10,12,18,]),'arg':([8,20,],[15,15,]),'formula':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> body IMPLIES head','formula',3,'p_formula','Interact.py',78),
  ('formula -> head','formula',1,'p_formula','Interact.py',79),
  ('body -> term','body',1,'p_body_1','Interact.py',86),
  ('body -> term COMMA body','body',3,'p_body_1','Interact.py',87),
  ('head -> term','head',1,'p_head','Interact.py',91),
  ('term -> NOT term','term',2,'p_term','Interact.py',95),
  ('term -> PRED LPAREN arg_seq RPAREN','term',4,'p_term','Interact.py',96),
  ('arg_seq -> arg','arg_seq',1,'p_argseq','Interact.py',103),
  ('arg_seq -> arg COMMA arg_seq','arg_seq',3,'p_argseq','Interact.py',104),
  ('arg -> VAR','arg',1,'p_arg','Interact.py',111),
  ('arg -> NUMBER','arg',1,'p_arg','Interact.py',112),
]
